### ISSUE TITLE
Training Model

### ISSUE THREAD

**Issue by AhmedTareka** [RomRoc/objdet_fizyr_colab#1]
Hi, 

The notebook is really interesting and helpful, however when I try to train the model with your dataset an error pops up as follows.

Creating model, this may take a second...
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 514, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 464, in main
    num_classes=train_generator.num_classes(),
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/csv_generator.py", line 170, in num_classes
    return max(self.classes.values()) + 1
ValueError: max() arg is an empty sequence

Hope you can help

Cheers
Tarek

**Comment by RomRoc** [comment]
Hello, I run notebook in Colab using Run -> Run all command, it doesn't give any error.
May be you didn't select Runtime type: Python3 / GPU. I don't see any other difference.
